apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dp
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Release.Name }}-ns
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-cont-api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: 8000
              name: http-api
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ .Release.Name }}-svc
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.37.0
          env:
            - name: REPORTER_GRPC_HOST_PORT
              value: {{ .Values.jaeger.collector.host }}
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
  replicas: 1


