apiVersion: v1 
kind: Service
metadata:
  name: {{ .Release.Name }}-adminer-svc
  namespace: {{ .Release.Name }}-ns
spec:
  selector:
    app: {{ .Release.Name }}-adminer
  ports:
    - name: {{ .Release.Name }}-adminer
      port: 8080
      nodePort: 30101
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc
  namespace: {{ .Release.Name }}-ns
spec:
  selector: 
    app: {{ .Release.Name }}-psql
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None