apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
  namespace: {{ .Release.Name }}-ns
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/postgresql
  storageClassName: manual


