{
 "title": "Api-Dash",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições Sucesso",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (endpoint_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Erro",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (endpoint_request_total{status=\"400\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resposas em (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (request_latency_seconds_bucket{app=\"api-app\"})",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (endpoint_request_total)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}